app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('user/role', array('uses' => 'UserController@roles','as' => 'user.role'));
Route::post('user/role_update/{id}', array('uses' => 'UserController@roleUpdate','as' => 'user.role_update'));
Route::resource('role', 'RoleController');
Route::resource('user', 'UserController');
Route::get('/', function()
{
	return View::make('hello');
});

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');
	
	public function roles()
	{
		return $this->belongsToMany('Role', 'role_user','user_id','role_id');
	}

}

app/controllers/UserController.php
<?php
use repositories\UserRepositoryInterface;
use Illuminate\Support\Facades\Input;
use cart\validators\UserValidator;
use cart\helper\FileHelper;

class UserController extends \BaseController {

	public $user;
	public $rules;
	
	public function __construct(UserRepositoryInterface $user)
	{
		$this->user = $user;
	}
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$users = User::paginate(5);
		return View::make('users.index', array('users' =>$users));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('users.create');
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$userValidator = new UserValidator($input);
		$validator = $userValidator->onStore();
		if ($validator->fails())
		{
			return Redirect::back()->withInput()->withErrors($validator);
		}
		$this->user->insert($input);
		return Redirect::to('user');
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$user = $this->user->find($id);
		return View::make('users.show', array('user' =>$user));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$user = $this->user->find($id);
		return View::make('users.edit', array('user' =>$user));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{

		$input = Input::except('image');
		$userValidator = new UserValidator($input);
		$file = new FileHelper();
		
		$validator = $userValidator->onUpdate($id);
		if ($validator->fails())
		{
			return Redirect::back()->withErrors($validator);
		}
		$image = $file->savefile(
				Request::file('image'), 
				Input::get('full_name').'_'.$id,'profile',
				array(array(150,150),array(500,500))
		);
		if($image){
			$input['image'] = $image;
		}
		$this->user->update($id, $input);
		return Redirect::to('user');
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$user = $this->user->find($id);
		$file = new FileHelper();
		$file->removeFile($user->image,'profile',array(array(150,150),array(500,500)));
		$this->user->delete($id);
	}
	
	/**
	 * 
	 */
	public function roles(){
		$user = $this->user->allWithRole();
		return View::make('users.role', array('user' => $user));
	}
	
	/**
	 * 
	 * @param int $id
	 */
	public function roleUpdate($id){
		$roles = Input::get('role');
		$this->user->updateUserRoles($id, $roles);
		return Redirect::to('user/role');
	}


}

app/views/users/create.blade.php
@extends('layout') @section('content') 
	<h3 class="ui dividing header">Accocunt Information</h3>
{{ Form::open(array('route'=>'user.store', 'class' => 'ui form segment')) }}
@if (count($errors->all()) > 0)
<div class="ui icon red message">
	<i class="close icon"></i>
	<i class="warning sign icon"></i>
	<div class="header">We're sorry</div>
		@foreach ($errors->all() as $message)
		    <p>{{ $message }}</p>
		@endforeach
</div>
@endif
<div class="">
	<div class="two fields">
		<div class="field">
			{{ Form::label('username', 'User name')}}
			<div class="ui icon input">
				{{ Form::text('username', $value = null, $attributes = array(
				'placeholder'=>"User name", 'id' => "username" )); }} <i
					class="user icon"></i>
			</div>
		</div>
		<div class="field">
			{{ Form::label('email', 'Email')}}
			<div class="ui icon input">
				{{ Form::email('email', $value = null, $attributes = array(
				'placeholder'=>"E-mail", 'id' => 'email' )); }} <i class="mail icon"></i>
			</div>
		</div>
	</div>
	<div class="field">
		{{ Form::label('password', 'Password')}}
		<div class="two fields">
			<div class="field">
				<div class="ui icon input">
					{{ Form::password('password', $value = null, $attributes = array(
					'placeholder'=>"password", 'id' => 'password' )); }} <i
						class="lock icon"></i>
				</div>
			</div>
			<div class="field">
				<div class="ui icon input">
					{{ Form::password('password_confirmation', $value = null, $attributes =
					array( 'placeholder'=>"Password again", 'id' => 'password_confirmation'
					)); }} <i class="lock icon"></i>
				</div>
			</div>
		</div>
	</div>
	<div class="two fields">
		<div class="field">
			{{ Form::label('dob', 'Date of birth')}}
			<div class="ui icon input">
				{{ Form::text('dob', $value = null, $attributes = array(
				'placeholder'=>"Date of birth", 'class' => "datepicker", 'id' =>
				'dob' )); }} <i class="Calendar icon"></i>
			</div>
		</div>
		<div class="field">
			<label>Sex</label>
			<div class="fields">
				<div class="field">
					<div class="ui radio">{{ Form::radio('sex','0', $attributes =
						array( 'checked' => "checked", 'id' => 'male' )); }} {{
						Form::label('sex', 'Male')}}</div>
				</div>
				<div class="field">
					<div class="ui radio">{{ Form::radio('sex','1', $attributes =
						array( 'checked' => "checked", 'id' => 'female' )); }} {{
						Form::label('', 'Female')}}</div>
				</div>
			</div>
		</div>
	</div>
	<div class="field">
		{{ Form::label('full_name', 'Full name')}}
		<div class="field">
			<div class="ui icon input">{{ Form::text('full_name', $value = null,
				$attributes = array( 'placeholder'=>"Full name", 'id' => 'full_name'
				)); }}</div>
		</div>
	</div>
	<div class="field">
		{{ Form::label('address', 'Address')}}
		<div class="field">
			<div class="ui icon input inline">
				{{ Form::text('address', $value = null, $attributes = array(
				'placeholder'=>"Full address", 'id' => 'address', )); }} <i
					class="home icon"></i>
			</div>
		</div>
	</div>
	<div class="two fields">
		<div class="field">
			{{ Form::label('city', 'City')}}
			<div class="ui icon input">{{ Form::text('city', $value = null,
				$attributes = array( 'placeholder'=>"City name", 'id' => "city" ));
				}}</div>
		</div>
		<div class="field">
			{{ Form::label('zip', 'ZIP')}}
			<div class="ui icon input">{{ Form::text('zip', $value = null,
				$attributes = array( 'placeholder'=>"ZIP code", 'id' => "zip" )); }}
			</div>
		</div>
	</div>
	{{ Form::submit('Register', $attributes = array( 'class' => "ui submit
	blue button" )); }}
	{{ link_to('user', 'Back', $attributes = array('class'=>"ui button black"), $secure = null); }}
</div>

{{ Form::close() }} @stop @section('script')
<script type="text/javascript">
$(document).ready(function() {
	$('.ui.form')
	.form({//v-required
		username: {
	    identifier : 'username',
	    rules: [
		      {
		          type   : 'empty',
		          prompt : 'Please enter your name'
		      }
	    	]
	  	},
	  	email: {
		    identifier : 'email',
		    rules: [
		      {
		        type   : 'email',
		        prompt : 'Please enter a valid e-mail'
		      }
		    ]
		  },
		password: {
		    identifier : 'password',
		    rules: [
		      {
		        type   : 'match[password_confirmation]',
		        prompt : 'Please enter a equal passwords'
		      },
	          {
	          	type   : 'empty',
	          	prompt : 'Please enter a password'
	          },
		    ]
		  },
		dob: {
	      identifier : 'dob',
	      rules: [
	        {
	          type   : 'date',
	          prompt : 'Please enter a valied date'
	        }
	      ]
	    },
	    full_name: {
		      identifier : 'full_name',
		      rules: [
		        {
		          type   : 'empty',
		          prompt : 'Please enter the full name'
		        }
		      ]
		 },
		 address: {
		      identifier : 'address',
		      rules: [
		        {
		          type   : 'empty',
		          prompt : 'Please enter the address'
		        }
		      ]
		    },
		 city: {
		      identifier : 'city',
		      rules: [
		        {
		          type   : 'empty',
		          prompt : 'Please enter the city'
		        }
		      ]
		    },
		zip: {
		      identifier : 'zip',
		      rules: [
		        {
		          type   : 'integer',
		          prompt : 'Please enter a valied zip code'
		        }
		      ]
		    },
        on: 'submit',
        inline: 'true',
	});
});

</script>
@stop

app/views/users/edit.blade.php
@extends('layout') @section('content') 

<h3 class="ui dividing header">Accocunt Information</h3>

{{ Form::model($user, array('route' => array('user.update', $user->id),'files' => true, 'method' => 'PUT', 'class' => 'ui form segment')) }}

@if (count($errors->all()) > 0)
<div class="ui icon red message">
	<i class="close icon"></i>
	<i class="warning sign icon"></i>
	<div class="header">We're sorry</div>
		@foreach ($errors->all() as $message)
		    <p>{{ $message }}</p>
		@endforeach
</div>
@endif
<div class="">
	<div class="field">
		{{ Form::label('image', 'Profile picture') }}
	</div>


<div  class="">
    
    {{ Form::im('image','uploads/profile/',array('id' => "profile")); }}   
</div>
<div id="progress" class="progress">
        <div class="progress-bar progress-bar-success"></div>
</div>		
	<div class="two fields">
		<div class="field">
			{{ Form::label('username', 'User name')}}
			<div class="ui icon input">
				{{ Form::text('username', $value = null, $attributes = array(
				'placeholder'=>"User name", 'id' => "username" )); }} <i
					class="user icon"></i>
			</div>
		</div>
		<div class="field">
			{{ Form::label('email', 'Email')}}
			<div class="ui icon input">
				{{ Form::email('email', $value = null, $attributes = array(
				'placeholder'=>"E-mail", 'id' => 'email' )); }} <i class="mail icon"></i>
			</div>
		</div>
	</div>
	<div class="field">
		{{ Form::label('password', 'Password')}}
		<div class="two fields">
			<div class="field">
				<div class="ui icon input">
					{{ Form::password('password', $value = null, $attributes = array(
					'placeholder'=>"password", 'id' => 'password' )); }} <i
						class="lock icon"></i>
				</div>
			</div>
			<div class="field">
				<div class="ui icon input">
					{{ Form::password('password_confirmation', $value = null, $attributes =
					array( 'placeholder'=>"Password again", 'id' => 'password_confirmation'
					)); }} <i class="lock icon"></i>
				</div>
			</div>
		</div>
	</div>
	<div class="two fields">
		<div class="field">
			{{ Form::label('dob', 'Date of birth')}}
			<div class="ui icon input">
				{{ Form::text('dob', $value = null, $attributes = array(
				'placeholder'=>"Date of birth", 'class' => "datepicker", 'id' =>
				'dob' )); }} <i class="Calendar icon"></i>
			</div>
		</div>
		<div class="field">
			<label>Sex</label>
			<div class="fields">
				<div class="field">
					<div class="ui radio">{{ Form::radio('sex','0', $attributes =
						array( 'checked' => "checked", 'id' => 'male' )); }} {{
						Form::label('sex', 'Male')}}</div>
				</div>
				<div class="field">
					<div class="ui radio">{{ Form::radio('sex','1', $attributes =
						array( 'checked' => "checked", 'id' => 'female' )); }} {{
						Form::label('', 'Female')}}</div>
				</div>
			</div>
		</div>
	</div>

	<div class="field">
		{{ Form::label('full_name', 'Full name')}}
		<div class="field">
			<div class="ui icon input">{{ Form::text('full_name', $value = null,
				$attributes = array( 'placeholder'=>"Full name", 'id' => 'full_name'
				)); }}</div>
		</div>
	</div>
	<div class="field">
		{{ Form::label('address', 'Address')}}
		<div class="field">
			<div class="ui icon input inline">
				{{ Form::text('address', $value = null, $attributes = array(
				'placeholder'=>"Full address", 'id' => 'address', )); }} <i
					class="home icon"></i>
			</div>
		</div>
	</div>
	<div class="two fields">
		<div class="field">
			{{ Form::label('city', 'City')}}
			<div class="ui icon input">{{ Form::text('city', $value = null,
				$attributes = array( 'placeholder'=>"City name", 'id' => "city" ));
				}}</div>
		</div>
		<div class="field">
			{{ Form::label('zip', 'ZIP')}}
			<div class="ui icon input">{{ Form::text('zip', $value = null,
				$attributes = array( 'placeholder'=>"ZIP code", 'id' => "zip" )); }}
			</div>
		</div>
	</div>
	{{ Form::submit('Update', $attributes = array( 'class' => "ui submit
	blue button" )); }}
	{{ link_to('user', 'Back', $attributes = array('class'=>"ui button black"), $secure = null); }}
</div>

{{ Form::close() }} @stop @section('script')
<script type="text/javascript">
$(document).ready(function() {
	$('.ui.form')
	.form({//v-required
		username: {
	    identifier : 'username',
	    rules: [
		      {
		          type   : 'empty',
		          prompt : 'Please enter your name'
		      }
	    	]
	  	},
	  	email: {
		    identifier : 'email',
		    rules: [
		      {
		        type   : 'email',
		        prompt : 'Please enter a valid e-mail'
		      }
		    ]
		  },
		password: {
		    identifier : 'password',
		    rules: [
		      {
		        type   : 'match[password_confirmation]',
		        prompt : 'Please enter a equal passwords'
		      },
		    ]
		  },
		dob: {
	      identifier : 'dob',
	      rules: [
	        {
	          type   : 'date',
	          prompt : 'Please enter a valied date'
	        }
	      ]
	    },
	    full_name: {
		      identifier : 'full_name',
		      rules: [
		        {
		          type   : 'empty',
		          prompt : 'Please enter the full name'
		        }
		      ]
		 },
		 address: {
		      identifier : 'address',
		      rules: [
		        {
		          type   : 'empty',
		          prompt : 'Please enter the address'
		        }
		      ]
		    },
		 city: {
		      identifier : 'city',
		      rules: [
		        {
		          type   : 'empty',
		          prompt : 'Please enter the city'
		        }
		      ]
		    },
		zip: {
		      identifier : 'zip',
		      rules: [
		        {
		          type   : 'integer',
		          prompt : 'Please enter a valied zip code'
		        }
		      ]
		    },
        on: 'submit',
        inline: 'true',
	});
});

</script>
@stop

app/views/users/index.blade.php
@extends('layout') @section('content')
<h3 class="ui dividing header">User list</h3>
{{ link_to('user/create', 'Add User', $attributes = array('class'=>"ui button green"), $secure = null); }}
<table class="ui striped table">
	<thead>
		<tr>
			<th class="six wide">Name</th>
			<th class="four wide">E-mail</th>
			<th class="six wide">Actions</th>
		</tr>
	</thead>
	<tbody>
		@foreach ($users as $user)
		<tr>
			<td>{{$user->full_name}}</td>
			<td>{{$user->email}}</td>
			<td>
			<div class="">
				{{ link_to_route('user.show', 'View',
				$parameters = array($user->id), 
				$attributes = array('class'=> "ui yellow button"),
				$secure = null); 
				}} 
				{{ link_to_route('user.edit', 'Edit',
				$parameters	= array($user->id), 
				$attributes = array('class'=> "ui blue button"),
				$secure = null); 
				}}
				{{ link_to_route('user.destroy', 'Delete',
				$parameters	= array($user->id), 
				$attributes = array('class'=> "ui red button delete"),
				$secure = null); 
				}}
			 </div>
			</td>
		</tr>
		@endforeach
	</tbody>
</table>
{{ $users->links(); }}

@stop
@stop @section('script')
<script type="text/javascript">
$(document).ready(function() {
	$(".delete").on('click',function(){
	   if (confirm("Press a button!") == true) {
			$.ajax({
				url: $(this).attr('href'),
				type: 'post',
				data: {_method: 'delete',},
				success:function(msg){
					location.reload();
				}
			});
			return false;
	    } else {
	        alert("You pressed Cancel!");
	    }

	});
});

</script>
@stop

app/views/users/role.blade.php
@extends('layout') @section('content') 

<h3 class="ui dividing header">Role Information</h3>

<table class="ui table">
  <thead>
    <tr>
      <th>User</th>
      <th>Role</th>
	  <th class="four wide">Actions</th>
    </tr>
  </thead>
  <tbody>
		@foreach ($user as $u)
		<tr>
		    <td>{{$u->email}}</td>
		    <td>
		    {{--*/ $suser = '' /*--}}
		    {{--*/ $auser = '' /*--}}
		    {{--*/ $uuser = '' /*--}}

		    @foreach ($u->roles as $r)
				@if ($r->role_id == 1)
				    {{--*/ $suser = 1 /*--}}
				@elseif ($r->role_id == 2)
				    {{--*/ $auser = 2 /*--}}
				@elseif ($r->role_id == 3)
				    {{--*/ $uuser = 3 /*--}}
				@endif
		    @endforeach
		    {{Form::open(array('route' => array('user.role_update', $u->id)))  }}
		    
		    {{ Form::checkbox('role[]', '1', $suser,array('id'=> $u->id.'_sa')) }}
		    {{ Form::label($u->id.'_sa', 'Super admin')}}
		    
		    {{ Form::checkbox('role[]', '2', $auser,array('id'=> $u->id.'_a')) }}
		    {{ Form::label($u->id.'_a', 'Admin')}}
		    
		    {{ Form::checkbox('role[]', '3', $uuser,array('id'=> $u->id.'_u')) }}
		    {{ Form::label($u->id.'_u', 'User')}}

		    </td>
			<td>
			<div class="">
			{{ Form::submit('Update', $attributes = array( 'class' => "ui submit
				blue button" )); }}
			 </div>
			 {{ Form::close() }}
			</td> 
		</tr>
		@endforeach
  </tbody>
</table>
{{ $user->links(); }}
@stop 
@section('script')
<script type="text/javascript">
$(document).ready(function() {

});

</script>
@stop

app/views/users/show.blade.php
@extends('layout') @section('content')
<h3 class="ui dividing header">User Information</h3>
<div class="segment">
	
	<ul class="ui raised segment">
		<li class="ui ribbon label">Name</li>
		<p>{{ $user->full_name}}</p>
		<li class="ui ribbon label">E-mail</li>
		<p>{{$user->email}}</p>
		<li class="ui ribbon label">Birth day</li>
		<p>{{ $user->dob}}</p>
		<li class="ui ribbon label">Sex</li>
		<p>@if ($user->sex == 1) Female	@else Male @endif</p>  
		<li class="ui ribbon label">Address</li>
		<p>{{ $user->address}}</p> 
		<li class="ui ribbon label">City</li>
		<p>{{ $user->city}}</p> 
		<li class="ui ribbon label">ZIP</li>
		<p>{{ $user->zip}}</p> 
	</ul>
{{ link_to('user', 'User', $attributes = array('class'=>"ui button black"), $secure = null); }}
</div>
@stop