app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('user/role', array('uses' => 'UserController@roles','as' => 'user.role'));
Route::post('user/role_update/{id}', array('uses' => 'UserController@roleUpdate','as' => 'user.role_update'));
Route::resource('role', 'RoleController');
Route::resource('user', 'UserController');
Route::get('/', function()
{
	return View::make('hello');
});

app/models/Role.php
<?php

class Role extends Eloquent {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'roles';
	
	/**
	 * Has many users
	 */
	public function users()
	{
		return $this->belongsToMany('User', 'role_user','role_id','user_id');
	}
}

app/controllers/RoleController.php
<?php

use repositories\RoleRepositoryInterface;
use repositories\UserRepositoryInterface;

class RoleController extends \BaseController {

	public $role;
	public $user;

	function __construct(RoleRepositoryInterface $role,UserRepositoryInterface $user){
		$this->role = $role;
		$this->user = $user;
	}
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$roles = $this->role->all();
		return View::make('roles.index', array('roles' =>$roles));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$role = $this->role->find($id);
		return View::make('roles.show', array('role' =>$role));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$role = $this->role->find($id);
		$user = $this->user->allWithRole($id);
		return View::make('roles.edit', array('role' =>$role,'user' => $user));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

app/controllers/api/RoleController.php
<?php

class api/RoleController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


}

app/views/roles/edit.blade.php
@extends('layout') @section('content') 

<h3 class="ui dividing header">Role Information</h3>

{{ Form::model($role, array('route' => array('role.update', $role->id),'files' => true, 'method' => 'PUT', 'class' => 'ui form segment')) }}

@if (count($errors->all()) > 0)
<div class="ui icon red message">
	<i class="close icon"></i>
	<i class="warning sign icon"></i>
	<div class="header">We're sorry</div>
		@foreach ($errors->all() as $message)
		    <p>{{ $message }}</p>
		@endforeach
</div>
@endif
<div class="">
	<div class="two fields">
		<div class="field">
			{{ Form::label('role', 'Role')}}
			<div class="field">
			{{ $role->role }}
			</div>
		</div>
		<div class="field">
			{{ Form::label('code', 'Code')}}
			<div class="field">
			{{ $role->code }}
			</div>
		</div>
	</div>
		@foreach ($user as $u)
		    <p>{{ $u->email }}{{$u->roles}}</p>
		    @foreach ($u->roles as $r)
		    	<li>{{ $r}}</li>
		    @endforeach
		@endforeach
	{{ Form::submit('Update', $attributes = array( 'class' => "ui submit
	blue button" )); }}
	{{ link_to('role', 'Back', $attributes = array('class'=>"ui button black"), $secure = null); }}
</div>

{{ Form::close() }} @stop @section('script')
<script type="text/javascript">
$(document).ready(function() {

});

</script>
@stop

app/views/roles/index.blade.php
@extends('layout')

@section('content')
<table class="ui table">
  <thead>
    <tr>
      <th>Role</th>
      <th>Code</th>
      <th class="six wide">Actions</th>
    </tr>
  </thead>
  <tbody>
	@foreach ($roles as $role)
    <tr>
      <td>{{$role->role}}</td>
      <td>{{$role->code}}</td>
      
			<td>
			<div class="">
				{{ link_to_route('role.show', 'View',
				$parameters = array($role->id), 
				$attributes = array('class'=> "ui yellow button"),
				$secure = null); 
				}} 
				{{ link_to_route('role.edit', 'Edit',
				$parameters	= array($role->id), 
				$attributes = array('class'=> "ui blue button"),
				$secure = null); 
				}}
			 </div>
			</td>     
    </tr>
	@endforeach
  </tbody>
</table>
@stop

app/views/roles/show.blade.php
@extends('layout') @section('content')
<h3 class="ui dividing header">Role Information</h3>
<div class="segment">
	
	<ul class="ui raised segment">
		<li class="ui ribbon label">Role</li>
		<p>{{ $role->role}}</p>
		<li class="ui ribbon label">Code</li>
		<p>{{$role->code}}</p>
		<li class="ui ribbon label">Users</li>
		@foreach ($role->users as $user)
		    <p>{{ $user->email}}</p>
		@endforeach
	</ul>
{{ link_to('role', 'Roles', $attributes = array('class'=>"ui button black"), $secure = null); }}
</div>
@stop